version: '3.5'

services:
  postgres-database:
    container_name: postgres-database
    image: postgres
    volumes:
       - postgres-database:/data/postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
    postgres-database: